---
title: "Codigo_Anna"
author: "Anna Cabrerizo Requena"
date: "2023-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Código Anna
# NAs

#interpolacion
```{r}
# Cargar la librería readr si no está cargada
library(readr)

# Cargar el DataFrame desde el archivo CSV
df <- read_csv("./data/join_datas.csv")

# Realizar la interpolación lineal para imputar NAs
# Puedes especificar las columnas donde deseas realizar la interpolación
# En este ejemplo, se realizará la interpolación en todas las columnas numéricas
df_numeric <- df %>% select_if(is.numeric)

# Aplicar la interpolación solo a las columnas numéricas
df_imputed <- df_numeric
for (col_name in colnames(df_numeric)) {
  df_imputed[[col_name]] <- approx(x = seq_along(df_imputed[[col_name]]), y = df_imputed[[col_name]], xout = seq_along(df_imputed[[col_name]]))$y
}

# Combinar las columnas numéricas interpoladas con las columnas no numéricas
df[, colnames(df_numeric)] <- df_imputed

# Guardar el DataFrame con los NAs imputados en un nuevo archivo CSV
write_csv(df, "join_data_imputed.csv")

```
<<<<<<< HEAD

```{r warning=FALSE}
library(tidyr)
library(tidyverse)

ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
ds_2t <- pivot_longer(ds2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')
ds_3t <- pivot_longer(ds3, -(PROVINCIA:MES),names_to = "DIA", values_to = "Cd", names_prefix = 'D')
ds_4t <- pivot_longer(ds4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
ds_5t <- pivot_longer(ds5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
ds_6t <- pivot_longer(ds6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM2.5", names_prefix = 'D')
ds_7t <- pivot_longer(ds7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')


ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "MAGNITUD")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "MAGNITUD")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "MAGNITUD")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "MAGNITUD")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "MAGNITUD")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "MAGNITUD")]

ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "PUNTO_MUESTREO")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "PUNTO_MUESTREO")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "PUNTO_MUESTREO")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "PUNTO_MUESTREO")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "PUNTO_MUESTREO")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "PUNTO_MUESTREO")]


z <- merge(ds_1t,ds_2t, all=TRUE)
z <- merge(z,ds_3t,all=TRUE)
z <- merge(z,ds_4t,all=TRUE)
z <- merge(z,ds_5t,all=TRUE)
z <- merge(z,ds_6t,all=TRUE)
z <- merge(z,ds_7t,all=TRUE)
```


```{r}
library(readxl)
meta_df <- read_excel("./data/2018/Metadatos/metainformacion_2018_tcm30-501408.xlsx", sheet="Estaciones evaluación 2018")
meta_df<-meta_df[meta_df$N_CCAA=='COMUNIDAD VALENCIANA',]
```


```{r}
library(dplyr)
library(tidyr)
z_2018<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2018<-z_2018[,columnas]
#view(z_2018)
```
   

# Para 2019
=======
>>>>>>> dc384e68f3d0c8565921bae71addfd59cb7d1a5f
```{r}
# Cargar las librerías necesarias
library(readr)
library(sp)
library(gstat)

# Cargar el DataFrame desde el archivo CSV
df <- read_csv("./data/join_datas.csv")

# Crear un objeto SpatialPoints
coordinates(df) <- ~ LONGITUD_G + LATITUD_G

# Especificar las coordenadas de los puntos a interpolar
# Puedes definir un nuevo DataFrame con las coordenadas donde deseas realizar la interpolación
# En este ejemplo, asumiremos que deseas interpolar en las mismas ubicaciones que ya tienes en 'df'
newdata <- df

# Realizar la interpolación utilizando IDW (Inverso de la Distancia Ponderada)
imputed_data <- idw(As ~ 1, df, newdata = newdata)

# Imputar los valores faltantes en la columna 'As' (puedes repetir el proceso para otras columnas)
df$As[is.na(df$As)] <- imputed_data[is.na(df$As)]

<<<<<<< HEAD
ds5 <- read_delim("data/2019/Datos_diarios/Pb_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds6 <- read_delim("data/2019/Datos_diarios/PM10_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds7 <- read_delim("data/2019/Datos_diarios/PM25_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)
```

```{r warning=FALSE}
library(tidyr)
library(tidyverse)

ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
ds_2t <- pivot_longer(ds2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')

ds_4t <- pivot_longer(ds4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
ds_5t <- pivot_longer(ds5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
ds_6t <- pivot_longer(ds6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM2.5", names_prefix = 'D')
ds_7t <- pivot_longer(ds7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')


ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "MAGNITUD")]

ds_4t <- ds_4t[, -which(names(ds_4t) == "MAGNITUD")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "MAGNITUD")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "MAGNITUD")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "MAGNITUD")]

ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "PUNTO_MUESTREO")]

ds_4t <- ds_4t[, -which(names(ds_4t) == "PUNTO_MUESTREO")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "PUNTO_MUESTREO")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "PUNTO_MUESTREO")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "PUNTO_MUESTREO")]

z <- merge(ds_1t,ds_2t, all=TRUE)

z <- merge(z,ds_4t,all=TRUE)
z <- merge(z,ds_5t,all=TRUE)
z <- merge(z,ds_6t,all=TRUE)
z <- merge(z,ds_7t,all=TRUE)

```

```{r}
library(readxl)
meta_df <- read_excel("./data/2019/Metadatos/metainformacion_2019_tcm30-513561.xlsx", sheet="Estaciones evaluación 2019")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
=======
# Guardar el DataFrame con los NAs imputados en un nuevo archivo CSV
write_csv(df, "join_data_imputed.csv")
>>>>>>> dc384e68f3d0c8565921bae71addfd59cb7d1a5f


```

<<<<<<< HEAD

```{r}
library(dplyr)
library(tidyr)
z_2019<-merge.data.frame(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2019<-z_2019[,columnas]
#view(z_2019)
```
    

# Para 2020
```{r}
library(readr)

ds1 <- read_delim("data/2020/Datos_diarios/As_DD_2020.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE, show_col_types = FALSE)

ds2 <- read_delim("data/2020/Datos_diarios/B(a)P_DD_2020.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds3 <- read_delim("data/2020/Datos_diarios/Cd_DD_2020.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds4 <- read_delim("data/2020/Datos_diarios/Ni_DD_2020.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds5 <- read_delim("data/2020/Datos_diarios/Pb_DD_2020.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds6 <- read_delim("data/2020/Datos_diarios/PM2.5_DD_2020.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds7 <- read_delim("data/2020/Datos_diarios/PM10_DD_2020.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)
```

```{r warning=FALSE}
library(tidyr)
library(tidyverse)

ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
ds_2t <- pivot_longer(ds2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')
ds_3t <- pivot_longer(ds3, -(PROVINCIA:MES),names_to = "DIA", values_to = "Cd", names_prefix = 'D')
ds_4t <- pivot_longer(ds4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
ds_5t <- pivot_longer(ds5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
ds_6t <- pivot_longer(ds6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM2.5", names_prefix = 'D')
ds_7t <- pivot_longer(ds7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')


ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "MAGNITUD")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "MAGNITUD")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "MAGNITUD")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "MAGNITUD")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "MAGNITUD")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "MAGNITUD")]

ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "PUNTO_MUESTREO")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "PUNTO_MUESTREO")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "PUNTO_MUESTREO")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "PUNTO_MUESTREO")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "PUNTO_MUESTREO")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "PUNTO_MUESTREO")]


z <- merge(ds_1t,ds_2t, all=TRUE)
z <- merge(z,ds_3t,all=TRUE)
z <- merge(z,ds_4t,all=TRUE)
z <- merge(z,ds_5t,all=TRUE)
z <- merge(z,ds_6t,all=TRUE)
z <- merge(z,ds_7t,all=TRUE)
```

```{r}
library(readxl)
meta_df <- read_excel("./data/2020/Metadatos/metainformacionestacionesymagnitudes2020_tcm30-531266.xlsx", 
    sheet = "Estaciones")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
```


```{r}
library(dplyr)
library(tidyr)
z_2020<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2020<-z_2020[,columnas]
#view(z_2020)
```
    
# Para 2021
```{r}
library(readr)

ds1 <- read_delim("data/2021/Datos_diarios/As_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE, show_col_types = FALSE)

ds2 <- read_delim("data/2021/Datos_diarios/BaP_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds3 <- read_delim("data/2021/Datos_diarios/Cd_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds4 <- read_delim("data/2021/Datos_diarios/Ni_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds5 <- read_delim("data/2021/Datos_diarios/Pb_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds6 <- read_delim("data/2021/Datos_diarios/PM10_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds7 <- read_delim("data/2021/Datos_diarios/PM25_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)
```

```{r warning=FALSE}
library(tidyr)
library(tidyverse)

ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
ds_2t <- pivot_longer(ds2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')
ds_3t <- pivot_longer(ds3, -(PROVINCIA:MES),names_to = "DIA", values_to = "Cd", names_prefix = 'D')
ds_4t <- pivot_longer(ds4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
ds_5t <- pivot_longer(ds5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
ds_6t <- pivot_longer(ds6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM2.5", names_prefix = 'D')
ds_7t <- pivot_longer(ds7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')


ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "MAGNITUD")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "MAGNITUD")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "MAGNITUD")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "MAGNITUD")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "MAGNITUD")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "MAGNITUD")]

ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "PUNTO_MUESTREO")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "PUNTO_MUESTREO")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "PUNTO_MUESTREO")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "PUNTO_MUESTREO")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "PUNTO_MUESTREO")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "PUNTO_MUESTREO")]


z <- merge(ds_1t,ds_2t, all=TRUE)
z <- merge(z,ds_3t,all=TRUE)
z <- merge(z,ds_4t,all=TRUE)
z <- merge(z,ds_5t,all=TRUE)
z <- merge(z,ds_6t,all=TRUE)
z <- merge(z,ds_7t,all=TRUE)
```

```{r}
library(readxl)
meta_df <- read_excel("./data/2021/Metadatos/metainformacion2021_tcm30-545563.xlsx", sheet="Estaciones")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
```


```{r}
library(dplyr)
library(tidyr)
z_2021<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2021<-z_2021[,columnas]
#view(z_2021)
```
    




# Para 2022
```{r}
library(readr)

ds1 <- read_delim("data/2022/Datos_diarios/As_DD_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE, show_col_types = FALSE)

ds2 <- read_delim("data/2022/Datos_diarios/B(a)P_DD_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds3 <- read_delim("data/2022/Datos_diarios/Cd_DD_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds4 <- read_delim("data/2022/Datos_diarios/Ni_DD_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds5 <- read_delim("data/2022/Datos_diarios/Pb_DD_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds6 <- read_delim("data/2022/Datos_diarios/PM2.5_DD_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)

ds7 <- read_delim("data/2022/Datos_diarios/PM10_DD_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  show_col_types = FALSE)
```

```{r warning=FALSE}
library(tidyr)
library(tidyverse)

ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
ds_2t <- pivot_longer(ds2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')
ds_3t <- pivot_longer(ds3, -(PROVINCIA:MES),names_to = "DIA", values_to = "Cd", names_prefix = 'D')
ds_4t <- pivot_longer(ds4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
ds_5t <- pivot_longer(ds5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
ds_6t <- pivot_longer(ds6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM2.5", names_prefix = 'D')
ds_7t <- pivot_longer(ds7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')


ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "MAGNITUD")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "MAGNITUD")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "MAGNITUD")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "MAGNITUD")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "MAGNITUD")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "MAGNITUD")]

ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "PUNTO_MUESTREO")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "PUNTO_MUESTREO")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "PUNTO_MUESTREO")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "PUNTO_MUESTREO")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "PUNTO_MUESTREO")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "PUNTO_MUESTREO")]


z <- merge(ds_1t,ds_2t, all=TRUE)
z <- merge(z,ds_3t,all=TRUE)
z <- merge(z,ds_4t,all=TRUE)
z <- merge(z,ds_5t,all=TRUE)
z <- merge(z,ds_6t,all=TRUE)
z <- merge(z,ds_7t,all=TRUE)
```

```{r}
library(readxl)
meta_df <- read_excel("./data/2022/Metadatos/Metainformacion2022.xlsx", sheet="Estaciones")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
```


```{r}
library(dplyr)
library(tidyr)
z_2022<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2022<-z_2022[,columnas]
#view(z_2022)
```
    
```{r}
z_2019$Cd<-as.numeric(NA)
z_final<-rbind(z_2018,z_2019,z_2020,z_2021,z_2022)
write.csv(z_final, "data/join_datas.csv")
```

=======
>>>>>>> dc384e68f3d0c8565921bae71addfd59cb7d1a5f
