---
title: "Luis"
author: "Luis Miguel Rioja Gallo"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(readr)
library(dplyr)
library(tidyr)
main_root<-'data'
carpetas<-c('2018','2019')#,'2020','2021','2022')
subcarpeta1<-'Datos_diarios'
for (c in carpetas){
  files<-dir(paste(main_root,c,subcarpeta1,sep='/'))
  df_t<-list()
  i=1
  for (file in files){
    ds1 <- read_delim(paste(main_root,c,subcarpeta1,file,sep='/'), 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
    ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = file, names_prefix = 'D')
    ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
    ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
    df_t[[i]]<-ds_1t
    i=i+1
    
  }
}


df_t[1]
```
```{r}
library(readr)

ds1 <- read_delim("data/2021/Datos_diarios/As_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds2 <- read_delim("data/2021/Datos_diarios/BaP_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds3 <- read_delim("data/2021/Datos_diarios/Cd_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds4 <- read_delim("data/2021/Datos_diarios/Ni_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds5 <- read_delim("data/2021/Datos_diarios/Pb_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds6 <- read_delim("data/2021/Datos_diarios/PM25_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds7 <- read_delim("data/2021/Datos_diarios/PM10_DD_2021.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

```{r warning=FALSE}
library(tidyr)
library(tidyverse)

ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
ds_2t <- pivot_longer(ds2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')
ds_3t <- pivot_longer(ds3, -(PROVINCIA:MES),names_to = "DIA", values_to = "Cd", names_prefix = 'D')
ds_4t <- pivot_longer(ds4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
ds_5t <- pivot_longer(ds5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
ds_6t <- pivot_longer(ds6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM2.5", names_prefix = 'D')
ds_7t <- pivot_longer(ds7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')


ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "MAGNITUD")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "MAGNITUD")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "MAGNITUD")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "MAGNITUD")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "MAGNITUD")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "MAGNITUD")]

ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "PUNTO_MUESTREO")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "PUNTO_MUESTREO")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "PUNTO_MUESTREO")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "PUNTO_MUESTREO")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "PUNTO_MUESTREO")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "PUNTO_MUESTREO")]


# ds_t <- bind_rows(ds_1t, ds_2t, ds_3t, ds_4t, ds_5t, ds_6t, ds_7t)

z <- merge(ds_1t,ds_2t)
z <- merge(z,ds_3t)
z <- merge(z,ds_4t)
z <- merge(z,ds_5t)
z <- merge(z,ds_6t)
z <- merge(z,ds_7t)
```



```{r}
library(readxl)
meta_df <- read_excel("data/2021/Metadatos/metainformacion2021_tcm30-545563.xlsx", 
    sheet = "Estaciones")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
```


```{r}
library(dplyr)
library(tidyr)
z2<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z2<-z2[,columnas]

```
    
```{r}
library(readr)
df <- read_csv("data/join_datas.csv")
```
```{r}
df_castellon<-ds_1t[ds_1t$PROVINCIA==12,]

```
    
```{r}
ds_1t
```
    
    