---
title: "Pruebas_Concatenar"
author: "Isaac Marti"
date: "2023-11-07"
output: html_document
---

# Lectura y limpieza del data set por años

## 2018

```{r}

library(readr)

ds1 <- read_delim("data/2018/As_DD_2018.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds2 <- read_delim("data/2018/B(a)P_DD_2018.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds3 <- read_delim("data/2018/Cd_DD_2018.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds4 <- read_delim("data/2018/Ni_DD_2018.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds5 <- read_delim("data/2018/Pb_DD_2018.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds6 <- read_delim("data/2018/PM2.5_DD_2018.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

ds7 <- read_delim("data/2018/PM10_DD_2018.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)


```


```{r}

library(tidyr)
library(tidyverse)

ds_1t <- pivot_longer(ds1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
ds_2t <- pivot_longer(ds2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')
ds_3t <- pivot_longer(ds3, -(PROVINCIA:MES),names_to = "DIA", values_to = "Cd", names_prefix = 'D')
ds_4t <- pivot_longer(ds4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
ds_5t <- pivot_longer(ds5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
ds_6t <- pivot_longer(ds6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM25", names_prefix = 'D')
ds_7t <- pivot_longer(ds7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')


ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "MAGNITUD")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "MAGNITUD")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "MAGNITUD")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "MAGNITUD")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "MAGNITUD")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "MAGNITUD")]

ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
ds_2t <- ds_2t[, -which(names(ds_2t) == "PUNTO_MUESTREO")]
ds_3t <- ds_3t[, -which(names(ds_3t) == "PUNTO_MUESTREO")]
ds_4t <- ds_4t[, -which(names(ds_4t) == "PUNTO_MUESTREO")]
ds_5t <- ds_5t[, -which(names(ds_5t) == "PUNTO_MUESTREO")]
ds_6t <- ds_6t[, -which(names(ds_6t) == "PUNTO_MUESTREO")]
ds_7t <- ds_7t[, -which(names(ds_7t) == "PUNTO_MUESTREO")]


z <- merge(ds_1t,ds_2t)
z <- merge(z,ds_3t)
z <- merge(z,ds_4t)
z <- merge(z,ds_5t)
z <- merge(z,ds_6t)
z <- merge(z,ds_7t)

```


## 2019


```{r}

library(readr)

da1 <- read_delim("data/2019/As_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

da2 <- read_delim("data/2019/BaP_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

da3 <- read_delim("data/2019/C6H6_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

da4 <- read_delim("data/2019/Ni_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

da5 <- read_delim("data/2019/Pb_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

da6 <- read_delim("data/2019/PM25_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

da7 <- read_delim("data/2019/PM10_DD_2019.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)


```


```{r}

library(tidyr)
library(tidyverse)

da_1t <- pivot_longer(da1, -(PROVINCIA:MES),names_to = "DIA", values_to = "As", names_prefix = 'D')
da_2t <- pivot_longer(da2, -(PROVINCIA:MES),names_to = "DIA", values_to = "BaP", names_prefix = 'D')
da_3t <- pivot_longer(da3, -(PROVINCIA:MES),names_to = "DIA", values_to = "D6H6", names_prefix = 'D')
da_4t <- pivot_longer(da4, -(PROVINCIA:MES),names_to = "DIA", values_to = "Ni", names_prefix = 'D')
da_5t <- pivot_longer(da5, -(PROVINCIA:MES),names_to = "DIA", values_to = "Pb", names_prefix = 'D')
da_6t <- pivot_longer(da6, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM10", names_prefix = 'D')
da_7t <- pivot_longer(da7, -(PROVINCIA:MES),names_to = "DIA", values_to = "PM25", names_prefix = 'D')


da_1t <- da_1t[, -which(names(da_1t) == "MAGNITUD")]
da_2t <- da_2t[, -which(names(da_2t) == "MAGNITUD")]
da_3t <- da_3t[, -which(names(da_3t) == "MAGNITUD")]
da_4t <- da_4t[, -which(names(da_4t) == "MAGNITUD")]
da_5t <- da_5t[, -which(names(da_5t) == "MAGNITUD")]
da_6t <- da_6t[, -which(names(da_6t) == "MAGNITUD")]
da_7t <- da_7t[, -which(names(da_7t) == "MAGNITUD")]

da_1t <- da_1t[, -which(names(da_1t) == "PUNTO_MUESTREO")]
da_2t <- da_2t[, -which(names(da_2t) == "PUNTO_MUESTREO")]
da_3t <- da_3t[, -which(names(da_3t) == "PUNTO_MUESTREO")]
da_4t <- da_4t[, -which(names(da_4t) == "PUNTO_MUESTREO")]
da_5t <- da_5t[, -which(names(da_5t) == "PUNTO_MUESTREO")]
da_6t <- da_6t[, -which(names(da_6t) == "PUNTO_MUESTREO")]
da_7t <- da_7t[, -which(names(da_7t) == "PUNTO_MUESTREO")]


z1 <- merge(da_1t,da_2t)
z1 <- merge(z1,da_3t)
z1 <- merge(z1,da_4t)
z1 <- merge(z1,da_5t)
z1 <- merge(z,da_6t)
z1 <- merge(z,da_7t)

```

```{r}

```

## 2019

## 2018

library(tidyr)
library(tidyverse)

ds_c <- rbind(ds1, ds2, ds3, ds4, ds5, ds6, ds7)

ds_t <- pivot_longer(ds_c, -(PROVINCIA:MES),names_to = "DIA", values_to = "VALOR", names_prefix = 'D')

```