---
title: "RMarkdown_Codigo"
author: "Luis Miguel Rioja Gallo"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(readxl)
main_root<-'data'
carpetas<-c('2019','2020','2021','2022')
subcarpeta1<-'Datos_diarios'
z_f<-list()
n=1
for (c in carpetas){
  files<-dir(paste(main_root,c,subcarpeta1,sep='/'))
  df_t<-list()
  n=n+1
  i=1
  for (file in files){
    ds1 <- read_delim(paste(main_root,c,subcarpeta1,file,sep='/'), 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
    ds1<-ds1[ds1$PROVINCIA==3|ds1$PROVINCIA==12|ds1$PROVINCIA==46,]
    ds_1t <- pivot_longer(ds1, -(PROVINCIA:DIA),names_to = "HORA", values_to = 'Valor', names_prefix = 'H')
    ds_1t <- ds_1t[, -which(names(ds_1t) == "MAGNITUD")]
    ds_1t <- ds_1t[, -which(names(ds_1t) == "PUNTO_MUESTREO")]
    ds_1t<-mutate(ds_1t,Fecha=ymd(paste(ANNO,MES,DIA,sep='-')))
    ds_1t<-select(ds_1t,-c('ANNO','MES','DIA'))
    ds_1t <- ds_1t %>% 
    group_by(Fecha,MUNICIPIO,PROVINCIA,ESTACION) %>%
    summarise(Valor=mean(Valor))
    new_name=strsplit(file,'_')[[1]][1]
    ds_1t[new_name]<-ds_1t$Valor
    ds_1t<-select(ds_1t,-c('Valor'))
    df_t[[i]]<-ds_1t
    i=i+1
  }
  
  z<-merge(df_t[1],df_t[2],all=TRUE)
  for (i in 3:length(df_t)){
    z<-merge(z,df_t[i],all=TRUE)
  }     
z_f[[n]]<-z
}


```


Cada elemento de la lista es un dataframe, el elemento 1 es del 2019 y asi hasta 2022.


    
# Para 2019


```{r}

meta_df <- read_excel("./data/2019/Metadatos/metainformacion_2019_tcm30-513561.xlsx", sheet="Estaciones evaluación 2019")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]


```


```{r}

z<-z_f[1]
z_2019<-merge.data.frame(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2019<-z_2019[,columnas]
#view(z_2019)
```
    

# Para 2020


```{r}

meta_df <- read_excel("./data/2020/Metadatos/metainformacionestacionesymagnitudes2020_tcm30-531266.xlsx", 
    sheet = "Estaciones")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
```


```{r}

z<-z_f[2]
z_2020<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2020<-z_2020[,columnas]
#view(z_2020)
```
    
# Para 2021

```{r}

meta_df <- read_excel("./data/2021/Metadatos/metainformacion2021_tcm30-545563.xlsx", sheet="Estaciones")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
```


```{r}

z<-z_f[3]
z_2021<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2021<-z_2021[,columnas]
#view(z_2021)
```
    
# Para 2022

```{r}

meta_df <- read_excel("./data/2022/Metadatos/Metainformacion2022.xlsx", sheet="Estaciones")
meta_df<-meta_df[meta_df$N_RED=='CCAA Com. Valenciana',]
unique(meta_df$PROVINCIA)
```


```{r}

z<-z_f[4]
z_2022<-merge(meta_df,z, by=c('PROVINCIA','MUNICIPIO','ESTACION'))
columnas<-c(colnames(z),'LATITUD_G','LONGITUD_G','ZONA')
z_2022<-z_2022[,columnas]
#view(z_2022)
```


    
```{r}
z_final<-rbind(z_2018,z_2019,z_2020,z_2021,z_2022)
#write.csv(z_final, "data/join_datas.csv")
```






















































